### Get the pools of a gambler
GET https://localhost:7289/gambler/01GY5F23AK9NEV1C4QVMWJC2NJ/pools HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiZXhwIjoxNzE2MzI2MDMyfQ.yBckrF8m-7WIrprpsSo3HTZ5hOtb1UIOqYiCTGLfmnw

### Get the gamblers of a pool
GET https://localhost:7289/pool/01FWY439D279KT6N8QS4E4PB0V/gamblers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiZXhwIjoxNzE2MzI2MDMyfQ.yBckrF8m-7WIrprpsSo3HTZ5hOtb1UIOqYiCTGLfmnw

### Get a pool
GET https://localhost:7289/pool/01FWY439D279KT6N8QS4E4PB0V HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiZXhwIjoxNzE2MzI2MDMyfQ.yBckrF8m-7WIrprpsSo3HTZ5hOtb1UIOqYiCTGLfmnw

### Get a list to bet
GET https://localhost:7289/pool/01FWY439D279KT6N8QS4E4PB0V/gambler/01GY5F23AK9NEV1C4QVMWJC2NJ/bets HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIwMUdZNUYyM0FLOU5FVjFDNFFWTVdKQzJOSiIsInVuaXF1ZV9uYW1lIjoiZmVsaXBlYXJwYSIsIm5iZiI6MTY4MzQyODcyNCwiZXhwIjoxNjg0MDMzNTI0LCJpYXQiOjE2ODM0Mjg3MjR9.70cYD9G7eHtv7Cj-UWIsY4weYvhNgr030A3COh4OkdM

### Set the bet for a match
PUT https://localhost:7289/bet HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIwMUdZNUYyM0FLOU5FVjFDNFFWTVdKQzJOSiIsInVuaXF1ZV9uYW1lIjoiZmVsaXBlYXJwYSIsIm5iZiI6MTY4MzQyODcyNCwiZXhwIjoxNjg0MDMzNTI0LCJpYXQiOjE2ODM0Mjg3MjR9.70cYD9G7eHtv7Cj-UWIsY4weYvhNgr030A3COh4OkdM
Content-Type: application/json

{
    "poolId": "01FWY439D279KT6N8QS4E4PB0V",
    "gamblerId": "01GY5F23AK9NEV1C4QVMWJC2NJ",
    "matchId": "01G7JCBE68BD2PR4MYA5MKVTHR",
    "homeTeamBet": 5,
    "awayTeamBet": 5
}