AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application
Resources:
  AuthGatewayHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        Authorizers:
          FirebaseAuthorizer:
            IdentitySource: $request.header.Authorization
            JwtConfiguration:
              issuer: https://securetoken.google.com/tyche-588ce
              audience:
                - tyche-588ce
        DefaultAuthorizer: FirebaseAuthorizer

  GetPoolById:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Felipearpa.Tyche.AmazonLambda::Felipearpa.Tyche.AmazonLambda.PoolFunctionWrapper::GetPoolById
      Runtime: dotnet8
      CodeUri: .
      MemorySize: 256
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource:
                - arn:aws:dynamodb:us-east-2:567776770335:table/Pool
      Architectures: [ arm64 ]
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            Path: /pools/{poolId}
            Method: GET
            ApiId: !Ref AuthGatewayHttpApi
  
  GetGamblersByPoolId:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Felipearpa.Tyche.AmazonLambda::Felipearpa.Tyche.AmazonLambda.PoolFunctionWrapper::GetGamblersByPoolId
      Runtime: dotnet8
      CodeUri: .
      MemorySize: 256
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource:
                - arn:aws:dynamodb:us-east-2:567776770335:table/Pool
                - arn:aws:dynamodb:us-east-2:567776770335:table/Pool/index/GetPoolGamblerScoresByPool-index
      Architectures: [ arm64 ]
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            Path: /pools/{poolId}/gamblers
            Method: GET
            ApiId: !Ref AuthGatewayHttpApi

  GetPoolGamblerScoreById:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Felipearpa.Tyche.AmazonLambda::Felipearpa.Tyche.AmazonLambda.PoolFunctionWrapper::GetPoolGamblerScoreById
      Runtime: dotnet8
      CodeUri: .
      MemorySize: 256
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource:
                - arn:aws:dynamodb:us-east-2:567776770335:table/Pool
      Architectures: [ arm64 ]
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            Path: /pools/{poolId}/gamblers/{gamblerId}
            Method: GET
            ApiId: !Ref AuthGatewayHttpApi
            
  GetPendingBets:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Felipearpa.Tyche.AmazonLambda::Felipearpa.Tyche.AmazonLambda.PoolFunctionWrapper::GetPendingBets
      Runtime: dotnet8
      CodeUri: .
      MemorySize: 256
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource:
                - arn:aws:dynamodb:us-east-2:567776770335:table/Pool
                - arn:aws:dynamodb:us-east-2:567776770335:table/Pool/index/GetPendingPoolGamblerBets-index
      Architectures: [ arm64 ]
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            Path: /pools/{poolId}/gamblers/{gamblerId}/bets/pending
            Method: GET
            ApiId: !Ref AuthGatewayHttpApi

Outputs:
  ApiURL:
    Description: API endpoint URL for Prod environment
    Value:
      Fn::Sub: https://${AuthGatewayHttpApi}.execute-api.${AWS::Region}.amazonaws.com/
