### Link an account
POST https://localhost:5000/account/link HTTP/1.1
content-type: application/json

{
    "email": "felipearcila@gmail.com",
    "externalAccountId": "ZaGjvMlgGxbhW0yK5mYK0Lg6Wl93"
}
