### Get Id Token
POST https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=AIzaSyC8Muo3PUYL6lHgXvZF0P1Pdj6TeUPKc9U 
Content-Type: application/json

{
    "email": "felipearcila@gmail.com",
    "password": "$Fearpa1332$",
    "returnSecureToken": true
}

### Get the active pool layouts
GET https://localhost:5002/pool-layouts/opened HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImZlNjVjY2I4ZWFkMGJhZWY1ZmQzNjE5NWQ2NTI4YTA1NGZiYjc2ZjMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdHljaGUtNTg4Y2UiLCJhdWQiOiJ0eWNoZS01ODhjZSIsImF1dGhfdGltZSI6MTc0ODM5Mzk4MCwidXNlcl9pZCI6IkRYcVhENklWMVhnVFc0MlJTZWtZNEFHamVkZjIiLCJzdWIiOiJEWHFYRDZJVjFYZ1RXNDJSU2VrWTRBR2plZGYyIiwiaWF0IjoxNzQ4MzkzOTgwLCJleHAiOjE3NDgzOTc1ODAsImVtYWlsIjoiZmVsaXBlYXJjaWxhQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJmZWxpcGVhcmNpbGFAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.K0_K-SerDnWrql5nIWfZ-IHVP4WqrKfDZGohtsbYqbY0cZTTFyveBfxmby6hVGq-VqeF5sZ86NdDe62F_AqPVaiJzhuW2cuZhKL7No2BzoCt4ICpZ7GjvuowZfZz5uw2KDXXJlxEgP3AxM_ueLUwPRRvNVPTTzadPZ6IUePu0HVsM3oV8W2b9GQJ4OcVRhU2SGwG1QamWKgCHvlHuNrkpP6loMJ7gZFiUyRqEYkBlqt4FwbRPB9H8lJXb4acC_GCYw0TK1uP1JFgl5JBoAiS0DrvldR9MSEj5QkJJWCtwGHRnKE8pWNnouxTg1Ig8cDXuIXATrCSEQhE1X6ICz7myQ
