### Get Id Token
POST https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=AIzaSyC8Muo3PUYL6lHgXvZF0P1Pdj6TeUPKc9U 
Content-Type: application/json

{
    "email": "test@tyche.com",
    "password": "test-password",
    "returnSecureToken": true
}

### Get the active pool layouts
GET https://localhost:5002/pool-layouts/opened HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImRmOGIxNTFiY2Q5MGQ1YjMwMjBlNTNhMzYyZTRiMzA3NTYzMzdhNjEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdHljaGUtNTg4Y2UiLCJhdWQiOiJ0eWNoZS01ODhjZSIsImF1dGhfdGltZSI6MTcxODI0MDg4OSwidXNlcl9pZCI6Im5Fa1NHWnJwS1BRbHh1Vm9kVHpaZlQzQUVpSTIiLCJzdWIiOiJuRWtTR1pycEtQUWx4dVZvZFR6WmZUM0FFaUkyIiwiaWF0IjoxNzE4MjQwODg5LCJleHAiOjE3MTgyNDQ0ODksImVtYWlsIjoidGVzdEB0eWNoZS5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsidGVzdEB0eWNoZS5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.UIz5BaUEpKjqSPC7d_SeRTN0diPVFa35DUs2doZF1k0R6rtfp2seDS_f4hAhNByHmTcFyZJYNbzLUK3OJ1aeHjJBrwbeylARzR9QPtuRje_bAI84QNIDmZUM8B1fOF--X5jrjD0LaDWt2wY1rX9YjmAoeselRdPCvlduekjVSM2IdC60EApm6BgeiwkGoJAgP_hU9owKIteKqoBePKYQ-LNmOxV0CU8__IQ0JHeN9sR_XaW6-PRdJdx8gmsGqwfSchuxN0l9KL7-31yQJ10484uTn_rmZ8j7_QflCEV0A-pzl_q0TowGbAm_6hzwfLVr5sf428HcV8dBswwAS0brvQ
