### Create a new user
POST https://localhost:7289/user HTTP/1.1
content-type: application/json

{
    "username": "felipearpa",
    "password": "#Fearpa1332#"
}

### Login an user
POST https://localhost:7289/user/login HTTP/1.1
content-type: application/json

{
    "username": "felipearpa",
    "password": "#Fearpa1332#"
}
