@baseUrl = https://wfykmbiop4.execute-api.us-east-2.amazonaws.com
# @baseUrl = https://localhost:7183

@authToken = Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjU3YmZiMmExMWRkZmZjMGFkMmU2ODE0YzY4NzYzYjhjNjg3NTgxZDgiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdHljaGUtNTg4Y2UiLCJhdWQiOiJ0eWNoZS01ODhjZSIsImF1dGhfdGltZSI6MTc1NTQ0NTk4NCwidXNlcl9pZCI6InNxVDJ1ZDJyd05iSWVUSWFIYXVPdkFBd25ORTIiLCJzdWIiOiJzcVQydWQycndOYkllVElhSGF1T3ZBQXduTkUyIiwiaWF0IjoxNzU1NDQ1OTg0LCJleHAiOjE3NTU0NDk1ODQsImVtYWlsIjoidHljaGUtYW5kcm9pZEB0eWNoZS5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsidHljaGUtYW5kcm9pZEB0eWNoZS5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.JFTaWYxWy4e-gkNREwkfRlNP59uOPjbxY-eFLqcM8bLYIqFTrsuvlDLAnAo8IRT-q2YwAqTapoIrm1l2NLuVZ8-NA5oI4o3nxho-1oOmiZ66AJo77aWB-RprgMu-1iyf8DgtR0QUCVGrmpp-0Rk8E5nchX_g9spYlSuLdcLKOm1xUn2zOmZpe06CZVMHgsi6INSWhzrQ1gLjzE8TC9vUcbl6pfAv8_WcEj0epzT8fwEFIBJKFH0bxE0mji4SlVeJGPiyII630LH8JEQw-XmKQ6MJHIoU7_jw0arDVPJ_TywtDVGbeRTJPvGyk9BgB3nEj5tWl8_Ocv8Gj_3ElklMdg


### Get a pool
GET {{baseUrl}}/pools/01H1CFJB0Y3KK357WCA2HB5MCX HTTP/1.1
Authorization: {{authToken}}


### Get the pool scores of a pool
GET {{baseUrl}}/pools/01H1CFJB0Y3KK357WCA2HB5MCX/gamblers HTTP/1.1
Authorization: {{authToken}}


### Get the pools of a gambler
GET {{baseUrl}}/gamblers/01K2WBEKVNGG7A5BZPM14QFFFS/pools HTTP/1.1
Authorization: {{authToken}}


### Get the pool score by id
GET {{baseUrl}}/pools/01H1CFJB0Y3KK357WCA2HB5MCX/gamblers/01H1CMCDHH99FH8FDY36S0YH3A HTTP/1.1
Authorization: {{authToken}}


### Get pendings bet
GET {{baseUrl}}/pools/01H1CFJB0Y3KK357WCA2HB5MCX/gamblers/01H1CMCDHH99FH8FDY36S0YH3A/bets/pending HTTP/1.1
Authorization: {{authToken}}


### Get finished bet
GET {{baseUrl}}/pools/01H1CFJB0Y3KK357WCA2HB5MCX/gamblers/01H1CMCDHH99FH8FDY36S0YH3A/bets/finished HTTP/1.1
Authorization: {{authToken}}


### Link an account
POST {{baseUrl}}/accounts
Authorization: {{authToken}}
Content-Type: application/json

{
    "email": "tyche@tyche.com",
    "externalAccountId": "MnW1eLzeDibEXOg1SmCVHvBznPn2"
}


### Create a pool
POST {{baseUrl}}/pools
Authorization: {{authToken}}
Content-Type: application/json

{
    "poolLayoutId": "01K23DN4Q5WD5BJ5FKGTG414EG",
    "poolName": "Champions League Pool",
    "ownerGamblerId": "01K23DN4Q5WD5BJ5FKGTG414EG"
}
