@baseUrl = https://wfykmbiop4.execute-api.us-east-2.amazonaws.com
@authToken = Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJiN2JhZmIyZjEwY2FlMmIxZjA3ZjM4MTZjNTQyMmJlY2NhNWMyMjMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdHljaGUtNTg4Y2UiLCJhdWQiOiJ0eWNoZS01ODhjZSIsImF1dGhfdGltZSI6MTc1NDUzMDMwMSwidXNlcl9pZCI6IkRYcVhENklWMVhnVFc0MlJTZWtZNEFHamVkZjIiLCJzdWIiOiJEWHFYRDZJVjFYZ1RXNDJSU2VrWTRBR2plZGYyIiwiaWF0IjoxNzU0NTMwMzAxLCJleHAiOjE3NTQ1MzM5MDEsImVtYWlsIjoiZmVsaXBlYXJjaWxhQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImZlbGlwZWFyY2lsYUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.aVU4d4pQWVkflMCpVVWTxG63ZhwX86wrVQbiD_BtT5Au5S_wNy3xCjJ2Zx8sj1R5LiZGebks7SSs3fkn4vrHC4Fuc0K0MM_Y8VXL64YIG5YiwlUf-95ujBlMzTEyH562yD4Y9qZOVkOqmm3V4i8iCt3MxQFRlKl6aiz776WkrYIa7-oPJFT-fCDWtwLxrfjmgNshFWlFTR5bGLsEhwl6O6qJ2IwfpaRZgOWKuOBZK_UcuyuZhoMdMT6CPfrdsBBnIfF08ZDzFLf08LsuSFL3trLgr1Ae7nHXywY_tXAWsvw9nwvFjlab4GBTaMEPOgjiEwQSnjpYpkQ-2UgLLZacJg

### Get a pool
GET {{baseUrl}}/pools/01H1CFJB0Y3KK357WCA2HB5MCX HTTP/1.1
Authorization: {{authToken}}

### Get the pool scores of a pool
GET {{baseUrl}}/pools/01H1CFJB0Y3KK357WCA2HB5MCX/gamblers HTTP/1.1
Authorization: {{authToken}}

### Get the pool score by id
GET {{baseUrl}}/pools/01H1CFJB0Y3KK357WCA2HB5MCX/gamblers/01H1CMCDHH99FH8FDY36S0YH3A HTTP/1.1
Authorization: {{authToken}}

### Get pendings bet
GET {{baseUrl}}/pools/01H1CFJB0Y3KK357WCA2HB5MCX/gamblers/01H1CMCDHH99FH8FDY36S0YH3A/bets/pending HTTP/1.1
Authorization: {{authToken}}

### Get finished bet
GET {{baseUrl}}/pools/01H1CFJB0Y3KK357WCA2HB5MCX/gamblers/01H1CMCDHH99FH8FDY36S0YH3A/bets/finished HTTP/1.1
Authorization: {{authToken}}
