### Get the pools of a gambler
GET https://localhost:5002/gambler/01H1CMCDHH99FH8FDY36S0YH3A/pools HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiZXhwIjoxNzE2MzI2MDMyfQ.yBckrF8m-7WIrprpsSo3HTZ5hOtb1UIOqYiCTGLfmnw

### Get the gamblers of a pool
GET https://localhost:5002/pool/01H1CFJB0Y3KK357WCA2HB5MCX/gamblers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiZXhwIjoxNzE2MzI2MDMyfQ.yBckrF8m-7WIrprpsSo3HTZ5hOtb1UIOqYiCTGLfmnw

### Get the PoolGamblerScore
GET https://localhost:5002/pools/01H1CFJB0Y3KK357WCA2HB5MCX/gamblers/01H1CMCDHH99FH8FDY36S0YH3A HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImJhNjI1OTZmNTJmNTJlZDQ0MDQ5Mzk2YmU3ZGYzNGQyYzY0ZjQ1M2UiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdHljaGUtNTg4Y2UiLCJhdWQiOiJ0eWNoZS01ODhjZSIsImF1dGhfdGltZSI6MTcxMTY2MTc4NSwidXNlcl9pZCI6Im5Fa1NHWnJwS1BRbHh1Vm9kVHpaZlQzQUVpSTIiLCJzdWIiOiJuRWtTR1pycEtQUWx4dVZvZFR6WmZUM0FFaUkyIiwiaWF0IjoxNzExNjYxNzg1LCJleHAiOjE3MTE2NjUzODUsImVtYWlsIjoidGVzdEB0eWNoZS5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsidGVzdEB0eWNoZS5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.cRf_9qN0k1mSkmfbibt-kqvu02T0dynBpklZbu-jpw4FPtVWgBpknCvxfvLr2kGYj9notCc5ipaSuleh_KW0d-9deru4xWqW8Hx7Udpq55TP-fukgC9Oz4iQd30I05V7PL2YAbEJWQ9UJfdmT9N4xTxEKXq38Ge8MnbCeifhYDqBhRH1-xGfPhvKNiw5VWCIWSqjSdyoJQRPASw3_ew__5BtVnLNu90sbhoAMJe-jgbtW6mzTmtN0VEJ89bmFTiii-2QHi0UvEr64ZJCFVv_8wIQhJ7MRFpUkEP2mzWMFtj6a8gMU6xqDx-cXfnkdr2UWZyJLJorfqEdQ90uP4pjHw

### Get a pool
GET https://localhost:5002/pool/01H1CFJB0Y3KK357WCA2HB5MCX HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiZXhwIjoxNzE2MzI2MDMyfQ.yBckrF8m-7WIrprpsSo3HTZ5hOtb1UIOqYiCTGLfmnw

### Get a list of pending bets
GET https://localhost:5002/pool/01H1CFJB0Y3KK357WCA2HB5MCX/gambler/01H1CMCDHH99FH8FDY36S0YH3A/bets HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiZXhwIjoxNzE2MzI2MDMyfQ.yBckrF8m-7WIrprpsSo3HTZ5hOtb1UIOqYiCTGLfmnw

### Set the bet for a match
PATCH https://localhost:5002/bet HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiZXhwIjoxNzE2MzI2MDMyfQ.yBckrF8m-7WIrprpsSo3HTZ5hOtb1UIOqYiCTGLfmnw
Content-Type: application/json

{
    "poolId": "01H1CFJB0Y3KK357WCA2HB5MCX",
    "gamblerId": "01H1CMCDHH99FH8FDY36S0YH3A",
    "matchId": "01H1FCNWBG30P448MK3DD595AR",
    "homeTeamBet": 2,
    "awayTeamBet": 1
}

### Create a pool from a pool layout
POST https://localhost:5001/pools HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjQ3YWU0OWM0YzlkM2ViODVhNTI1NDA3MmMzMGQyZThlNzY2MWVmZTEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdHljaGUtNTg4Y2UiLCJhdWQiOiJ0eWNoZS01ODhjZSIsImF1dGhfdGltZSI6MTc1MTgxNzQ1OSwidXNlcl9pZCI6IkRYcVhENklWMVhnVFc0MlJTZWtZNEFHamVkZjIiLCJzdWIiOiJEWHFYRDZJVjFYZ1RXNDJSU2VrWTRBR2plZGYyIiwiaWF0IjoxNzUxODE3NDU5LCJleHAiOjE3NTE4MjEwNTksImVtYWlsIjoiZmVsaXBlYXJjaWxhQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJmZWxpcGVhcmNpbGFAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.zB54nfVMybzLVixU3onQCZ9opzp4jQA1xlVV9fWQsMz9HT6EvmkqLvJwrmlkJSwzQpoAChIJY342Rui-QEDzN4rTAVlBhO5Yc0_q8HHrkGQCPGkpBG4IknticIjyUkmj6tLNtdwCli2vmVUCgprADUIPlrkn7iTRdEIKq1IYmqquFMBdPk5VSE8lY1kPUagWfQVNkhDj2ee-xmOo6shbZau-QQHjxTgYCRFM6M1ch8jANks6yHttriOH5RQB1ofT1MY5aCM79UfF_1D4BfDhr-Or-tRZ7obInPfrf8S_xK9NV08lJVlFCpNaZJt-wzLspDEUmfB4yFgjsWVj32VG1g
Content-Type: application/json

{
    "poolLayoutId":"01HY8V7VXGPNN8CS5QY8AVMZ2C",
    "poolName":"pool naming for testing",
    "ownerGamblerId":"01H1CMCDHH99FH8FDY36S0YH3A"
}
